### ISSUE TITLE
Broken links for stats and explorer

### ISSUE THREAD

**Issue by kevinsimper** [filecoin-project/docs#3]
Both links does not seem to work. The first is blank and the second gives 404.

https://docs.filecoin.io/go-filecoin-tutorial/Getting-Started.html#start-streaming-activity-from-your-node

**Comment by djpecot** [comment]
Hey Kevin,

Seems like the block explorer linke moved [here](http://user.kittyhawk.wtf:8000/)

**Comment by har00ga** [comment]
I have the block explorer link fixed in an upcoming PR, there will soon be a dedicated network stat page that links to the various community metrics tools as well. I'll make sure the other link will be swapped with the location of that once completed
