### ISSUE TITLE
Remove duplicate info about the Filecoin network (not implementation-specific)

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/docs#7]
Since the implementation of the new non-implementation-specific docs site (hosted at https://docs.filecoin.io and generated by the `filecoin-project/filecoin-docs` repo), there's now overlap with some of the introductory conceptual documentation presented here in the go-filecoin tutorial (hosted at https://go.filecoin.io). 

We should now assume, like we do with lotu.sh, that people who come here are looking specifically for info on the specific implementation and have gotten their conceptual background already. 

I'd recommend that we review the content here to determine what belongs at docs.filecoin.io and whether it's already there or needs to be ported over, leaving pointers here where helpful. 

Note: Changes to the markdown files happen in this repo, but changes to the config.js file (for the sidebar) happen in the `metadocs` repo.

cc @mishmosh for any additional guidance here.

**Comment by har00ga** [comment]
Resolved with #15 :)
